### ISSUE TITLE
about to implement AdaCode?

### ISSUE THREAD

**Issue by zelenooki87** [chaiNNer-org/spandrel#142]
Thanks to you developers for all your hard work and a job well done. I'd love to see the adacode architecture in one of the next builds. This project is based on the femasr architecture, so I don't think there will be any problems integrating it as well. Thank you very much!
https://github.com/kechunl/AdaCode

**Comment by RunDevelopment** [comment]
Okay, so I looked into this arch, and I kinda don't want to touch it due to licensing issues. 

[FeMaSR](https://github.com/chaofengc/FeMaSR) was published under CC-BY-NC-SA and [AdaCode](https://github.com/kechunl/AdaCode) under MIT. MIT is **not** compatible with CC-BY-NC-SA, so MIT just doesn't work as license for a derivative work of FeMaSR, AFAIK.

I'll make an issue to talk to them about it.

**Comment by zelenooki87** [comment]
Can you add an option for successful conversion of the AdaCode model to ONNX format for faster inference? I manage to convert from PyTorch to ONNX with FeMaSR, while for AdaCode it is unfeasible. Thank you.

**Comment by joeyballentine** [comment]
Are you getting an error? We don't control whether models can be converted to onnx, that's entirely on the pytorch/onnx side

**Comment by zelenooki87** [comment]
I don’t get any error, but after 7-8 minutes I gave up waiting for the model to convert. FeMaSR converts in a few minutes. I’ll try again, I’ll give it a chance for a longer time to convert, maybe that’s the cause.

**Comment by zelenooki87** [comment]
I apologize, it was just that. It just needed to wait a little longer. Is there a chance to convert the bsr_grl_base.safetensors model to ONNX? ( https://drive.google.com/file/d/1JdzeTFiBVSia7PmSvr5VduwDdLnirxAG/view?usp=sharing ) I get an error when converting it: Error
An unexpected error occurred: Error: The application encountered an unexpected error and could not continue.
Thanks
