### ISSUE TITLE
Spandrel doesn't support bf16

### ISSUE THREAD

**Issue by joeyballentine** [chaiNNer-org/spandrel#163]
Noticed from this PR here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14794 (OP if you're reading this please make an issue here next time)

> bfloat16 is non-functional as-is, since passing a bfloat16 model to spandrel results in float/bfloat16 mismatch errors

**Comment by RunDevelopment** [comment]
> OP if you're reading this please make an issue here next time

Ping them @joeyballentine

---

Reading through the PR, I have no idea what the issue even is. How is bf16 not supported? Spandrel doesn't do anything dtype casting. It's the user's responsibility to ensure that the tensor to upscale has the right dtype. 

And what does "passing a bfloat16 model to spandrel" mean? Spandrel loads and creates models, so how can you pass a model to spandrel?

So yeah. I have no idea what this issue is about, and bf16 works in chainner AFAIK.

**Comment by joeyballentine** [comment]
bf16 isn't an option in chaiNNer, you're thinking of regular fp16

**Comment by joeyballentine** [comment]
closed this as it is probably not actually an issue
