### ISSUE TITLE
CodeFormer Support

### ISSUE THREAD

**Issue by TraceIvan** [chaiNNer-org/spandrel#202]
In the newest version 0.3.0, it doesn't support CodeFormer anymore.
![image](https://github.com/chaiNNer-org/spandrel/assets/27859479/6cb4b754-b72c-4c63-a7d2-83137b9cbd84)

**Comment by joeyballentine** [comment]
It is supported, you just need to install spandrel_extra_arches as described here: https://github.com/chaiNNer-org/spandrel?tab=readme-ov-file#more-architectures

This change was made due to certain architecture code having restrictive licenses that makes them unsuitable for certain projects, so these are now opt-in archs
